"""Server-rendered English and Hebrew content for the public landing page."""

LANDING_CONTENT = {
    "en": {
        "title": "CareIL — Calm clinic management for therapists",
        "description": "CareIL helps independent therapists manage clients, appointments, session summaries, secure portal links and Google Calendar in Hebrew and English.",
        "og_description": "Your clients, calendar and therapeutic work in one calm, secure space.",
        "nav_aria": "Main navigation", "features_link": "Features", "preview_link": "Preview",
        "login": "Log in", "start": "Sign up", "language": "עברית",
        "eyebrow": "Made for independent therapists",
        "hero_title": "Your clinic work,", "hero_emphasis": "held in one calm space.",
        "hero_text": "Manage clients, appointments, session summaries and secure communication without losing the human feeling of your practice.",
        "create_clinic": "Create your clinic", "demo": "Try the live demo",
        "demo_note": "No real client information is used in the demo. Demo workspaces expire automatically.",
        "preview_aria": "CareIL dashboard preview", "hello": "Hey, Karin",
        "welcome": "WELCOME BACK", "glance": "Your clinic at a glance", "date": "Tuesday, 25 August",
        "stats": ["Active clients", "Appointments", "Requests"],
        "schedule": ["Client appointment", "Parent guidance", "Client appointment"],
        "trust": ["Hebrew & English", "Mobile friendly", "Google Calendar", "Private tenant workspace"],
        "features_eyebrow": "Everything connected", "features_title": "Less administration.",
        "features_emphasis": "More room for care.",
        "features": [
            ("Clients and therapeutic work", "Keep client details, appointment summaries, files and history together in one organized record."),
            ("Scheduling that knows your hours", "Set availability and session duration, manage requests and synchronize confirmed sessions with Google Calendar."),
            ("Secure client communication", "Send appointment details and short-lived portal links without exposing private clinic records."),
            ("Designed for phone and desktop", "Use CareIL comfortably from the clinic, home or phone, in English or Hebrew."),
        ],
        "product_preview": "Product preview", "clear_screens": "Clear on every screen.",
        "preview_text": "The desktop dashboard keeps the whole clinic visible; compact mobile cards keep essential actions within reach.",
        "desktop_nav": "Calendar · Clients · Settings", "edit_profile": "Edit · Profile",
        "callout_eyebrow": "Made especially for the Israeli clinic",
        "callout_title": "Calm, clear and human clinic management.",
        "callout_text": "Clients, appointments, session summaries and secure communication — in Hebrew and English, from every device.",
        "final_title": "Ready to give your clinic more space?", "create_account": "Create an account", "open_demo": "Open demo",
        "privacy": "Privacy", "terms": "Terms", "accessibility": "Accessibility", "cookies": "Cookies", "contact": "Contact",
    },
    "he": {
        "title": "CareIL — ניהול קליניקה רגוע למטפלים",
        "description": "CareIL מסייעת למטפלים עצמאיים לנהל לקוחות, פגישות, סיכומי טיפול, קישורי פורטל מאובטחים ו-Google Calendar בעברית ובאנגלית.",
        "og_description": "הלקוחות, היומן והעבודה הטיפולית שלך במרחב אחד רגוע ומאובטח.",
        "nav_aria": "ניווט ראשי", "features_link": "תכונות", "preview_link": "תצוגה מקדימה",
        "login": "כניסה", "start": "הרשמה", "language": "English",
        "eyebrow": "נבנה עבור מטפלות ומטפלים עצמאיים",
        "hero_title": "עבודת הקליניקה שלך,", "hero_emphasis": "במרחב אחד רגוע.",
        "hero_text": "ניהול לקוחות, פגישות, סיכומי טיפול ותקשורת מאובטחת — בלי לאבד את התחושה האנושית של הקליניקה.",
        "create_clinic": "פתיחת הקליניקה שלי", "demo": "התנסות בדמו",
        "demo_note": "הדמו אינו מכיל מידע אמיתי של לקוחות וסביבת ההדגמה נמחקת אוטומטית.",
        "preview_aria": "תצוגה מקדימה של לוח הבקרה", "hello": "היי, קארין",
        "welcome": "ברוכה השבה", "glance": "הקליניקה שלך במבט אחד", "date": "יום שלישי, 25 באוגוסט",
        "stats": ["לקוחות פעילים", "פגישות", "בקשות"],
        "schedule": ["פגישה טיפולית", "הדרכת הורים", "פגישה טיפולית"],
        "trust": ["עברית ואנגלית", "מותאם לנייד", "Google Calendar", "סביבה פרטית לכל מטפל"],
        "features_eyebrow": "הכול מחובר", "features_title": "פחות ניהול.",
        "features_emphasis": "יותר מקום לטיפול.",
        "features": [
            ("לקוחות ועבודה טיפולית", "פרטי לקוחות, סיכומי פגישות, קבצים והיסטוריה טיפולית נשמרים יחד ברשומה אחת מסודרת."),
            ("יומן שמכיר את שעות הקליניקה", "מגדירים זמינות ומשך פגישה, מנהלים בקשות ומסנכרנים פגישות מאושרות עם Google Calendar."),
            ("תקשורת מאובטחת עם לקוחות", "שולחים פרטי פגישה וקישורי פורטל קצרי תוקף בלי לחשוף את הרשומות הפרטיות של הקליניקה."),
            ("מותאם לטלפון ולמחשב", "עובדים בנוחות מהקליניקה, מהבית או מהטלפון — בעברית או באנגלית."),
        ],
        "product_preview": "הצצה למערכת", "clear_screens": "ברור ונוח בכל מסך.",
        "preview_text": "לוח הבקרה מציג את כל הקליניקה במחשב, וכרטיסים קומפקטיים שומרים את הפעולות החשובות נגישות גם בנייד.",
        "desktop_nav": "יומן · לקוחות · הגדרות", "edit_profile": "עריכה · פרופיל",
        "callout_eyebrow": "נבנה במיוחד לקליניקה הישראלית",
        "callout_title": "ניהול קליניקה רגוע, ברור ואנושי.",
        "callout_text": "לקוחות, פגישות, סיכומי טיפול וקשר מאובטח — בעברית ובאנגלית, מכל מכשיר.",
        "final_title": "מוכנים לתת לקליניקה יותר מרחב?", "create_account": "יצירת חשבון", "open_demo": "פתיחת הדמו",
        "privacy": "פרטיות", "terms": "תנאי שימוש", "accessibility": "נגישות", "cookies": "עוגיות", "contact": "יצירת קשר",
    },
}
